version: '3.8'

services:
  chatmood:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - DEBUG=true
      - LOG_LEVEL=debug
    volumes:
      - ./web:/root/web
      - ./logs:/var/log/chatmood
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching (future feature)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    profiles:
      - redis

  # Optional: PostgreSQL for persistent storage (future feature)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: chatmood
      POSTGRES_USER: chatmood
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-chatmood123}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    profiles:
      - database

volumes:
  redis_data:
  postgres_data:

networks:
  default:
    name: chatmood_network
